// src/data/modelConfigs/agnes.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent —— 来源：Agnes Video V2.0 官方文档
//    (C:\Users\Administrator\Desktop\ag.txt)
// 本文件为「草稿模块」，尚未并入生产。请勿直接编辑生产配置；确认后由人工接入
// models 表 / MODEL_REGISTRY / GenerationBar.resolveTemplate。
//
// NEEDS_CONFIRM 项（文档未定义，勿臆造）：
//   - qualities：官方文档未提及任何质量档位（低/标准/高），故留空待确认。
//   - maxReferenceImages：关键帧模式用 extra_body.image 数组，但文档未给数量上限。
//
// 并入时需注意的「适配器差异」（待对齐）：
//   - 现有 server/providers/video/shared.cjs 用 VIDEO_TIER_SCALE = {1k,2k,3k,4k}，
//     而官方文档明确标准分辨率档位为 480p / 720p / 1080p。并入时需把 480p/720p/1080p
//     映射到现有 tier，或改造适配器以接受官方档位名。
//   - 文档 num_frames ≤ 441、frame_rate 推荐 24 → 最长 ≈18s；现有前端时长档写死到 10s
//     （GenerationBar DEFAULT_DURATIONS），并入后 Agnes 前台时长档必须含 18s。

import type { VideoModelConfig } from './schema';

export const agnesVideoModels: VideoModelConfig[] = [
  {
    modelId: 'agnes-video-v2.0',
    displayName: 'Agnes 视频 V2.0',
    officialFamily: 'Agnes',
    docsUrl: 'https://wiki.agnes-ai.cn/llms.txt',
    supportedParams: {
      // 文档 mode 参数仅 ti2vid（图生）与 keyframes（关键帧）；文生无需 mode。
      videoModes: ['t2v', 'i2v_first', 'keyframes'],
      // 文档「参数标准化」明确三个标准分辨率档位。
      videoResolutions: ['480p', '720p', '1080p'],
      // 文档「推荐画幅」表列出的 5 个比例；任意尺寸也会被服务端自动映射。
      ratios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
      // 文档「视频时长控制」目标时长表：81/121/241/441 帧 @24fps → 3/5/10/18 秒。
      durationsSec: [3, 5, 10, 18],
      // 文档 frame_rate 支持 1–60，示例与推荐均为 24。
      frameRate: 24,
      // 文档硬性约束：num_frames ≤ 441 且遵循 8n+1。
      maxNumFrames: 441,
      // 文档未定义质量档位 → 留空待确认（见文件头 NEEDS_CONFIRM）。
      // qualities: NEEDS_CONFIRM
      // 文档未给参考图/关键帧数量上限 → 留空待确认（见文件头 NEEDS_CONFIRM）。
      // maxReferenceImages: NEEDS_CONFIRM
    },
    notes:
      '官方文档 Agnes Video V2.0：文生视频 + 图生视频(ti2vid) + 关键帧动画(keyframes)；' +
      '异步任务 API（POST /v1/videos → GET /agnesapi?video_id=）；Bearer 鉴权；' +
      '结果在 metadata.url，尺寸标准化信息在 metadata.size_mapping。' +
      '时长公式 seconds = num_frames / frame_rate，num_frames≤441 且 8n+1。' +
      '定价：标准 $0.005/秒，当前 $0/秒（平台对用户仍按固定 credit_cost 计费，互不影响）。',
  },
];
