// src/data/modelConfigs/cogvideox.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const cogvideoxVideoModels: VideoModelConfig[] = [
  {
    modelId: 'cogvideox-1.5-5b-i2v',
    displayName: '智谱 CogVideoX 1.5-5B (I2V)',
    officialFamily: 'CogVideoX',
    docsUrl: 'https://github.com/THUDM/CogVideo',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'], // 1.5-5B(-I2V)
      videoResolutions: ['1360x768'],
      durationsSec: [5, 10], // 5–10s
      frameRate: 16, // HTML：16fps
      // ratios: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes:
      '智谱 CogVideoX（清影同源开源）：CogVideoX-2B/5B/1.5-5B(-I2V)；5–10s·16fps·1360×768；' +
      '单卡可推理（BF16 约 9GB）。GitHub 推理/微调 + HuggingFace 权重；商业版「清影」。' +
      '来源：汇总 HTML（二手）。',
  },
];
