// src/data/modelConfigs/firefly.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const fireflyVideoModels: VideoModelConfig[] = [
  {
    modelId: 'adobe-firefly-video',
    displayName: 'Adobe Firefly Video',
    officialFamily: 'Firefly',
    docsUrl: 'https://helpx.adobe.com/firefly/web/work-with-audio-and-video/work-with-video/',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['1080p'],
      frameRate: 24, // HTML：1080p·24fps
      ratios: ['16:9', '9:16', '1:1'], // HTML：16:9/9:16/1:1
      // durationsSec: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes:
      'Adobe Firefly Video：文本/图像→视频；1080p·24fps；16:9/9:16/1:1；' +
      '仅用已授权内容（Adobe Stock/公有领域）训练，可商用。Firefly 内还可切换 Veo、Sora 2、Runway Gen-4.5、Pika 等合作模型。' +
      '来源：汇总 HTML（二手），时长档待官方原文确认。',
  },
];
