// src/data/modelConfigs/hunyuanvideo.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const hunyuanVideoModels: VideoModelConfig[] = [
  {
    modelId: 'hunyuanvideo-1.5',
    displayName: '腾讯 HunyuanVideo 1.5',
    officialFamily: 'HunyuanVideo',
    docsUrl: 'https://github.com/Tencent-Hunyuan/HunyuanVideo-1.5',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['480p', '720p', '1080p'],
      // durationsSec: NEEDS_CONFIRM（HTML 未给时长）
      // ratios: NEEDS_CONFIRM
      // frameRate: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes:
      '腾讯 HunyuanVideo 1.5（8.3B）：文生/图生视频；480p·720p·1080p；消费级 GPU 可跑；' +
      '生态 ComfyUI/Diffusers/LightX2V/TeaCache。开源（tencent-hunyuan-community）。' +
      '来源：汇总 HTML（二手），时长/画幅/帧率待官方原文确认。',
  },
];
