// src/data/modelConfigs/kling.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const klingVideoModels: VideoModelConfig[] = [
  {
    modelId: 'kling-3.0',
    displayName: '可灵 Kling 3.0',
    officialFamily: 'Kling',
    docsUrl: 'https://www.klingai.com/document-api/',
    supportedParams: {
      videoModes: ['i2v_first', 'i2v_first_last', 'reference_image'], // 图生、首尾帧、主体(Elements)参考
      videoResolutions: ['4k'], // 最高 4K；低档 NEEDS_CONFIRM
      durationsSec: [10], // 最高 4K·10s；短档 NEEDS_CONFIRM
      maxReferenceImages: 1, // 图生/首尾帧输入图（主体参考另计，待确认）
      // qualities: NEEDS_CONFIRM
    },
    notes:
      '快手可灵 Kling 3.0 / 3.0 Omni / v2.6：图生视频、首尾帧、动作控制 3.0、主体（Elements）参考；最高 4K·10s。' +
      '接口 api-beijing.klingai.com，Bearer 鉴权，异步任务。' +
      '注：文档核心能力列未明示文生，故 t2v 未列入——如官方支持待确认。来源：汇总 HTML（二手）。',
  },
];
