// src/data/modelConfigs/luma.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const lumaVideoModels: VideoModelConfig[] = [
  {
    modelId: 'luma-ray-3.2',
    displayName: 'Luma Ray 3.2',
    officialFamily: 'Luma',
    docsUrl: 'https://docs.lumalabs.ai/docs/video-generation',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first', 'i2v_first_last'], // 首尾帧
      videoResolutions: ['540p', '4k'], // 540p→4K
      // durationsSec: NEEDS_CONFIRM（HTML 仅说 5s+，未给明确上限）
      // ratios: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes:
      'Luma Dream Machine Ray 2 / Ray 2 Flash / Ray 3.2（Agents API）：文本/图像→视频；' +
      '分辨率 540p→4K；时长 5s+（具体上限待官方原文确认）；支持概念运镜（concepts）、首尾帧、视频扩展。' +
      '图像生成、视频修改（风格迁移/改框/配音）、Webhook。来源：汇总 HTML（二手）。',
  },
];
