// src/data/modelConfigs/minimax.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const minimaxVideoModels: VideoModelConfig[] = [
  {
    modelId: 'MiniMax-H3',
    displayName: 'MiniMax 海螺 H3',
    officialFamily: 'MiniMax',
    docsUrl: 'https://platform.minimax.io/docs/guides/video-generation',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first_last', 'reference_image'], // 文生、首尾帧、参考生视频
      videoResolutions: ['768p', '2k'],
      durationsSec: [4, 15], // 4–15s 整数秒任选（见 notes）
      maxReferenceImages: 12, // 图/视频/音频≤12 文件
      // qualities: NEEDS_CONFIRM
    },
    notes:
      'MiniMax 海螺 H3（开放多模态）/ Hailuo-2.3 / 02 系列：文生视频、首尾帧、参考生视频（图/视频/音频≤12 文件）；' +
      '768P/2K；4–15s 整数秒；异步三步（创建→轮询→下载）。来源：汇总 HTML（二手）。',
  },
];
