// src/data/modelConfigs/pika.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const pikaVideoModels: VideoModelConfig[] = [
  {
    modelId: 'pika-2.2',
    displayName: 'Pika 2.2',
    officialFamily: 'Pika',
    docsUrl: 'https://pikaslabs.com/',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['1080p'],
      durationsSec: [10], // 最长 10s；Pikaframes 最长 25s（见 notes）
      ratios: ['16:9', '9:16', '1:1'], // HTML：7 种画幅（16:9/9:16/1:1 等），其余 NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
      // maxReferenceImages: NEEDS_CONFIRM
    },
    notes:
      'Pika 2.2/2.5：文生/图生视频；最长 10s·1080p；7 种画幅（16:9/9:16/1:1 等，其余待确认）。' +
      '工具：Pikaframes（2–5 图转视频，最长 25s）、Pikaswaps、Pikadditions、Pikaffects。' +
      '公开 API 仍在开发中；fal.ai 等第三方已暴露 Pika 模型接口。来源：汇总 HTML（二手）。',
  },
];
