// src/data/modelConfigs/runway.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
//    注：Runway 卡片内提及的 Seedance 2.0 为字节模型，已归入 seedance.ts，此处不重复。
import type { VideoModelConfig } from './schema';

export const runwayVideoModels: VideoModelConfig[] = [
  {
    modelId: 'runway-gen-4.5',
    displayName: 'Runway Gen-4.5',
    officialFamily: 'Runway',
    docsUrl: 'https://docs.dev.runwayml.com/',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first', 'video_edit'],
      videoResolutions: ['720p'],
      durationsSec: [10], // HTML：Gen-4.5 720p 最长 10s；短档 NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
      // frameRate: NEEDS_CONFIRM
    },
    notes:
      'Runway Gen-4.5：日常视频生成，720p，最长 10s（$0.12/s）。文/图/视频编辑。' +
      '官方 SDK（Node/Python），企业级 SLA、零数据留存。来源：汇总 HTML（二手）。',
  },
  {
    modelId: 'runway-aleph-2.0',
    displayName: 'Runway Aleph 2.0',
    officialFamily: 'Runway',
    docsUrl: 'https://docs.dev.runwayml.com/',
    supportedParams: {
      videoModes: ['video_edit', 'keyframes'], // 文本/关键帧编辑已有视频
      durationsSec: [30], // HTML：Aleph 编辑最长 30s（$0.28/s）
      // videoResolutions: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes: 'Runway Aleph 2.0：文本/关键帧编辑已有视频，最长 30s。来源：汇总 HTML（二手）。',
  },
];
