// src/data/modelConfigs/seedance.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
//    ⚠️ 重要：此前 DB 中 doubao-seedance-* / seededit-* / seeddream-* 被误标 type=text，
//       并入时务必改回 video（Seedance/SeedEdit）与 image（SeedDream/即梦图像）。
import type { VideoModelConfig } from './schema';

export const seedanceVideoModels: VideoModelConfig[] = [
  {
    modelId: 'jimeng_t2v_v30',
    displayName: '即梦 Jimeng T2V V3.0',
    officialFamily: 'Seedance',
    docsUrl: 'https://www.volcengine.com/docs/82379/1520757',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first', 'i2v_first_last', 'reference_image'], // 文生/图生首尾帧/多模态参考
      videoResolutions: ['480p', '720p', '1080p', '4k'], // 480p→4K
      durationsSec: [15], // 最高 4K·15s；智能时长档待官方原文确认 → NEEDS_CONFIRM
      maxReferenceImages: 9, // 多模态参考：图 0–9 + 视频 0–3 + 音频 0–3
      // qualities: NEEDS_CONFIRM
    },
    notes:
      '字节即梦/Seedance（火山引擎方舟）：jimeng_t2v_v30、Doubao Seedance 2.0/1.5/1.0。' +
      '文生/图生（首尾帧）/多模态参考生视频（图 0–9 + 视频 0–3 + 音频 0–3）；最高 4K·15s；' +
      '支持日/印尼/西/葡等多语言提示词。⚠️ 此前 DB 中 doubao-seedance-* 等被误标 type=text，' +
      '须并入时改为 video（SeedDream 系列为图像，改 image）。来源：汇总 HTML（二手），智能时长档待官方原文确认。',
  },
];
