// src/data/modelConfigs/sora.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const soraVideoModels: VideoModelConfig[] = [
  {
    modelId: 'sora-2',
    displayName: 'Sora 2',
    officialFamily: 'Sora',
    docsUrl: 'https://developers.openai.com/api/docs/guides/video-generation',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['720p', '1080p', '1080x1920'],
      durationsSec: [20], // 最长 20s（HTML：最长 20s）；短档待官方原文确认 → NEEDS_CONFIRM
      maxReferenceImages: 1, // 图生（首帧）输入 1 张
      // qualities: NEEDS_CONFIRM（HTML 未提质量档）
      // frameRate: NEEDS_CONFIRM
      // maxNumFrames: NEEDS_CONFIRM
    },
    notes:
      'OpenAI Sora 2 / 2 Pro：文本/图像→视频+同步音频；最长 20s；720p/1080p/竖屏 1080x1920；' +
      '支持扩展、Remix、角色创建。异步任务 REST v1/videos（创建→轮询/Webhook→获取）。' +
      '来源：汇总 HTML（二手），时长短档与质量档待官方原文确认。',
  },
  {
    modelId: 'sora-2-pro',
    displayName: 'Sora 2 Pro',
    officialFamily: 'Sora',
    docsUrl: 'https://developers.openai.com/api/docs/guides/video-generation',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['720p', '1080p', '1080x1920'],
      durationsSec: [20],
      maxReferenceImages: 1,
    },
    notes: 'Sora 2 Pro：同 Sora 2 能力，含快照版本。来源：汇总 HTML（二手）。',
  },
];
