// src/data/modelConfigs/svd.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const svdVideoModels: VideoModelConfig[] = [
  {
    modelId: 'svd-1.1',
    displayName: 'Stable Video Diffusion 1.1',
    officialFamily: 'StableVideo',
    docsUrl: 'https://platform.stability.ai/docs/getting-started/stable-video',
    supportedParams: {
      videoModes: ['i2v_first'], // 图生视频
      videoResolutions: ['1024x576', '768x768', '576x1024'],
      durationsSec: [2], // 约 2s·25 帧
      frameRate: 25,
      maxNumFrames: 25,
      // qualities: NEEDS_CONFIRM
    },
    notes:
      'Stability AI SVD 1.1：图生视频；约 2s·25 帧；1024×576/768×768/576×1024；' +
      '运动强度控制、种子可控、MP4 输出。⚠️ 托管 API 已于 2025-07-24 正式停用，' +
      '当前仅支持自托管（下载权重 + 参考实现）。来源：汇总 HTML（二手）。',
  },
];
