// src/data/modelConfigs/veo.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const veoVideoModels: VideoModelConfig[] = [
  {
    modelId: 'veo-3.1-generate-preview',
    displayName: 'Veo 3.1 Generate',
    officialFamily: 'Veo',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/veo',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['720p', '1080p'],
      frameRate: 24, // HTML：720p·1080p·24fps
      // durationsSec: NEEDS_CONFIRM（HTML 未给具体时长档）
      // qualities: NEEDS_CONFIRM
      // maxNumFrames: NEEDS_CONFIRM
    },
    notes:
      'Google Veo 3.1：文本/图像→含音频视频；720p·1080p·24fps；文生/图生；支持参考图、提示词改写。' +
      '多档模型 generate/fast/lite；入口 Gemini API（开发者）与 Vertex AI（企业）。来源：汇总 HTML（二手），时长档待官方原文确认。',
  },
  {
    modelId: 'veo-3.1-fast',
    displayName: 'Veo 3.1 Fast',
    officialFamily: 'Veo',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/veo',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['720p', '1080p'],
      frameRate: 24,
    },
    notes: 'Veo 3.1 fast 档。来源：汇总 HTML（二手）。',
  },
  {
    modelId: 'veo-3.1-lite',
    displayName: 'Veo 3.1 Lite',
    officialFamily: 'Veo',
    docsUrl: 'https://ai.google.dev/gemini-api/docs/veo',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first'],
      videoResolutions: ['720p', '1080p'],
      frameRate: 24,
    },
    notes: 'Veo 3.1 lite 档。来源：汇总 HTML（二手）。',
  },
];
