// src/data/modelConfigs/vidu.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const viduVideoModels: VideoModelConfig[] = [
  {
    modelId: 'viduq2-pro',
    displayName: 'Vidu Q2 Pro',
    officialFamily: 'Vidu',
    docsUrl: 'https://docs.platform.vidu.cn/',
    supportedParams: {
      videoModes: ['t2v', 'reference_image'], // 参考生视频（主体库一致性）；文生假设支持（标注）
      videoResolutions: ['540p', '1080p'],
      durationsSec: [10], // 最长 10s
      ratios: ['16:9', '9:16', '4:3', '3:4', '1:1'],
      // qualities: NEEDS_CONFIRM
      // maxReferenceImages: NEEDS_CONFIRM
    },
    notes:
      '生数科技 Vidu：viduq2-pro / viduq2 / viduq1 / vidu2.0/1.5。参考生视频（主体库一致性）、音视频直出（audio）、错峰模式；' +
      '最长 10s；540p→1080p；16:9/9:16/4:3/3:4/1:1。注：文档侧重参考生，t2v 是否支持待官方原文确认。' +
      '来源：汇总 HTML（二手）。',
  },
];
