// src/data/modelConfigs/wan.ts
// ⚠️ AUTO-GENERATED by video-model-config-agent
//    来源：视频模型官方文档汇总 HTML（二手汇编，链接指向各厂商官方文档）
//          C:\Users\Administrator\WorkBuddy\2026-08-09-21-38-46\视频模型官方文档汇总.html
//    ⚠️ 草稿模块，尚未并入生产。接入前须以官方原文复核（此为二手整理，精度和实时性有限）。
//    NEEDS_CONFIRM：汇编未定义的字段，勿臆造，待官方原文确认。
import type { VideoModelConfig } from './schema';

export const wanVideoModels: VideoModelConfig[] = [
  {
    modelId: 'wan2.7',
    displayName: '通义万相 Wan 2.7',
    officialFamily: 'Wan',
    docsUrl: 'https://help.aliyun.com/zh/document_detail/3025059.html',
    supportedParams: {
      videoModes: ['t2v', 'i2v_first', 'reference_image'], // 文生/图生/参考生；原生多模态
      videoResolutions: ['1080p'], // 1080p+
      durationsSec: [15], // 最长 15s；短档 NEEDS_CONFIRM
      // ratios: NEEDS_CONFIRM
      // qualities: NEEDS_CONFIRM
    },
    notes:
      '阿里通义万相 Wan 2.5/2.6/2.7：文生/图生/参考生视频；原生多模态（文/图/音频/视频）；' +
      '音画同步、多镜头叙事、角色扮演；最长 15s·1080p+。阿里云百炼（DashScope）/通义万相官网，按地域 Endpoint 调用。' +
      '来源：汇总 HTML（二手）。',
  },
];
